# -*- coding: utf-8 -*-
"""CRDC_2017_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XMc9YTVCK3Ai-0tYG-tjbrJymEngqxVb

# 2017-18 Arrests Civil Rights Data Collection

***👥 About Dataset***

[Dataset](https://catalog.data.gov/dataset/2017-18-arrests-civil-rights-data-collection) from data.gov.
'This set of Excel file contains data on student referrals to law enforcement by disability and student-related arrests by disability for all states. It also contains data on incidents of offenses by type of offense for all states.' (OCR)

***❔ Research Questions***

**Part 1**
1. Which types of offenses are most common nationally?
2. Which states have the highest overall referral and arrest rates?
3. What proportion of referrals result in an arrest by state?

**Part 2**
1. ~~Are students with disabilities represented differently in arrests compared to referrals?~~

2. Which states show the largest disparity in referral and arrest representation between students with and without disabilities?

## Data Cleaning and Preparation
"""

!pip install pandas openpyxl

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import the datasets from Google drive
from google.colab import drive

drive.mount('/content/drive')

# Convert xslx file into csv file
xlsx_file = '/content/drive/MyDrive/Ana Garcia Work Folder/Civil Rights Arrest - Analysis/Offenses.xlsx'
csv_file = "Offenses.csv"

# Convert Offense.csv to pdf
df = pd.read_excel(xlsx_file)

df.to_csv(csv_file, index=False)

print(f"Successfully converted xsls file to csv file")

# Convert xslx file into csv file for datasets with and without disabilities
xlsx_files = ('/content/drive/MyDrive/Ana Garcia Work Folder/Civil Rights Arrest - Analysis/Referred-disability-and-no.xlsx',
             '/content/drive/MyDrive/Ana Garcia Work Folder/Civil Rights Arrest - Analysis/Arrest-disability-and-no.xlsx')
csv_names = ("Referred-disability-and-no.csv", "Arrest-disability-and-no.csv")

# Function to clean col names
def clean_column(col_name):
    col_name = str(col_name)
    # Remove trailing numbers
    col_name = re.sub(r'(\d+)$', '', col_name)
    # Replace spaces, slashes, special characters with underscore
    col_name = re.sub(r'[ /]', '_', col_name)
    # Remove repeated underscores
    col_name = re.sub(r'__+', '_', col_name)
    # Remove leading/trailing underscores
    col_name = col_name.strip('_')
    # Lowercase for consistency
    col_name = col_name.lower()
    return col_name

# Loop through the files and create csv files for each
for xlsx_file_path, csv_file_name in zip(xlsx_files, csv_names):
  # The first three rows are meant to be the header for these specific Excel files
  # This will create a MultiIndex header for the DataFrame
  df = pd.read_excel(xlsx_file_path, header=[0, 1, 2])

 # Fill missing header levels with previous non-NaN value
  filled_cols = []
  for col in df.columns:
      new_col = []
      last_val = ""
      for val in col:
          if pd.isna(val) or "Unnamed" in str(val):
              new_col.append(last_val)
          # Rename columns with Race/Ethnicity -> Race of Students with and without disabilities
          elif "Race/Ethnicity" in str(val):
              new_col.append("Race/Ethnicity of Students with and without disabilities")
          else:
              new_val = str(val).strip()
              new_col.append(new_val)
              last_val = new_val
      filled_cols.append(new_col)

  # Flatten headers and remove consecutive duplicates
  df.columns = [
      "_".join([v for i, v in enumerate(new_col) if i == 0 or v != new_col[i-1]])
      for new_col in filled_cols
  ]

  # Save cleaned CSV
  df.to_csv(csv_file_name, index=False)

  print(f"Successfully converted {xlsx_file_path} to {csv_file_name}")

# Convert xslx file into csv file for datasets with disabilities
xlsx_files = ('/content/drive/MyDrive/Ana Garcia Work Folder/Civil Rights Arrest - Analysis/Referred-disability.xlsx',
                    '/content/drive/MyDrive/Ana Garcia Work Folder/Civil Rights Arrest - Analysis/Arrest-disability.xlsx')
csv_names = ('Referred-disability.csv', 'Arrest-disability.csv')


# Loop through the files and create csv files for each
for xlsx_file_path, csv_file_name in zip(xlsx_files, csv_names):
  # The first three rows are meant to be the header for these specific Excel files
  # This will create a MultiIndex header for the DataFrame
  df = pd.read_excel(xlsx_file_path, header=[0, 1, 2])

 # Fill missing header levels with previous non-NaN value
  filled_cols = []
  for col in df.columns:
      new_col = []
      last_val = ""
      for val in col:
          if pd.isna(val) or "Unnamed" in str(val):
              new_col.append(last_val)
          # Rename columns with Race/Ethnicity -> Race of Students with and without disabilities
          elif "Race/Ethnicity" in str(val):
              new_col.append("Race/Ethnicity of Students with disabilities")
          else:
              new_val = str(val).strip()
              new_col.append(new_val)
              last_val = new_val
      filled_cols.append(new_col)

  # Flatten headers and remove consecutive duplicates
  df.columns = [
      "_".join([v for i, v in enumerate(new_col) if i == 0 or v != new_col[i-1]])
      for new_col in filled_cols
  ]

  # Save cleaned CSV
  df.to_csv(csv_file_name, index=False)

  print(f"Successfully converted {xlsx_file_path} to {csv_file_name}")

# Convert xslx file into csv file for datasets without disabilities
xlsx_files = ('/content/drive/MyDrive/Ana Garcia Work Folder/Civil Rights Arrest - Analysis/Referred-no-disability.xlsx',
              '/content/drive/MyDrive/Ana Garcia Work Folder/Civil Rights Arrest - Analysis/Arrest-no-disability.xlsx')
csv_names = ('Referred-no-disability.csv', 'Arrest-no-disability.csv')

# Function to clean col names
def clean_column(col_name):
    col_name = str(col_name)
    # Remove trailing numbers
    col_name = re.sub(r'(\d+)$', '', col_name)
    # Replace spaces, slashes, special characters with underscore
    col_name = re.sub(r'[ /]', '_', col_name)
    # Remove repeated underscores
    col_name = re.sub(r'__+', '_', col_name)
    # Remove leading/trailing underscores
    col_name = col_name.strip('_')
    # Lowercase for consistency
    col_name = col_name.lower()
    return col_name

# Loop through the files and create csv files for each
for xlsx_file_path, csv_file_name in zip(xlsx_files, csv_names):
  # The first three rows are meant to be the header for these specific Excel files
  # This will create a MultiIndex header for the DataFrame
  df = pd.read_excel(xlsx_file_path, header=[0, 1, 2])

 # Fill missing header levels with previous non-NaN value
  filled_cols = []
  for col in df.columns:
      new_col = []
      last_val = ""
      for val in col:
          if pd.isna(val) or "Unnamed" in str(val):
              new_col.append(last_val)
          # Rename columns with Race/Ethnicity -> Race of Students with and without disabilities
          elif "Race/Ethnicity" in str(val):
              new_col.append("Race/Ethnicity of Students without disabilities")
          else:
              new_val = str(val).strip()
              new_col.append(new_val)
              last_val = new_val
      filled_cols.append(new_col)

  # Flatten headers and remove consecutive duplicates
  df.columns = [
      "_".join([v for i, v in enumerate(new_col) if i == 0 or v != new_col[i-1]])
      for new_col in filled_cols
  ]

  # Save cleaned CSV
  df.to_csv(csv_file_name, index=False)

  print(f"Successfully converted {xlsx_file_path} to {csv_file_name}")

"""### Cleaning 'Offenses' dataset"""

# Look into offense dataset
offense = pd.read_csv('/content/Offenses.csv')
offense.head()

offense.info()

# Covert object columns into integers
for col in offense.columns:
    if offense[col].dtype == "object" and col != "State":
        offense[col] = (
            offense[col]
            .str.replace(",", "", regex=False)  # remove commas
            .str.replace("%", "", regex=False)  # remove percent signs
        )
        offense[col] = pd.to_numeric(offense[col], errors="coerce")

# Check
offense.info()

"""### Cleaning 'Referred to law enforcement' datasets"""

# Look into referred to law enforcement datasets
referred_disability_and_no = pd.read_csv('/content/Referred-disability-and-no.csv')
referred_disability = pd.read_csv('/content/Referred-disability.csv')
referred_no_disability = pd.read_csv('/content/Referred-no-disability.csv')

referred_disability_and_no.head()

# Remove columns where there is 'Percent' present for all datasets (except Offenses)
referred = ['referred_disability_and_no', 'referred_disability', 'referred_no_disability']

for df in referred:
  columns_to_drop = [col for col in globals()[df].columns if 'Percent' in col]
  globals()[df] = globals()[df].drop(columns=columns_to_drop)

referred_disability.info()

# Covert object columns into integers
for df in referred:
  for col in globals()[df].columns:
    if globals()[df][col].dtype == "object" and col != "State":
      globals()[df][col] = (
          globals()[df][col]
          .str.replace(",", "", regex=False)
          .str.replace("%", "", regex=False)
      )
      globals()[df][col] = pd.to_numeric(globals()[df][col], errors="coerce")

referred_no_disability.info()

"""### Cleaning 'School-Related Arrests' datasets"""

# Look into school-related arrests dataset
arrests_disability_and_no = pd.read_csv('/content/Arrest-disability-and-no.csv')
arrests_disability = pd.read_csv('/content/Arrest-disability.csv')
arrests_no_disability = pd.read_csv('/content/Arrest-no-disability.csv')

arrests_disability_and_no.head()

# Remove columns where there is 'Percent' present for all datasets (except Offenses)
arrests = ['arrests_disability_and_no', 'arrests_disability', 'arrests_no_disability']

for df in arrests:
  columns_to_drop = [col for col in globals()[df].columns if 'Percent' in col]
  globals()[df] = globals()[df].drop(columns=columns_to_drop)

# Covert object columns into integers
for df in arrests:
  for col in globals()[df].columns:
    if globals()[df][col].dtype == "object" and col != "State":
      globals()[df][col] = (
          globals()[df][col]
          .str.replace(",", "", regex=False)
          .str.replace("%", "", regex=False)
      )
      globals()[df][col] = pd.to_numeric(globals()[df][col], errors="coerce")

arrests_disability_and_no.info()

"""## Part 1: Offense & Enforcement Patterns

### Question 1: Which type of offenses are most common nationally?

Based on the national totals in the dataset, the most common types of school offenses are:
1. Physical attack without a weapon
2. Threats of physical attack without a weapon
3. Robbery without a weapon

Across all 50 states, the District of Columbia, and Puerto Rico, incidents without a weapon are consistently reported more frequently than those involving a weapon. In fact, approximately 99.8% of schools reported at least one type of incident, indicating that these non-weapon-related offenses are widespread nationally.
"""

# To find the answer to this, we must look into the first row of the dataset.

highest_offense = offense.iloc[0]
highest_offense

# Sort float values from greatest to least to get top offenses, excluding the 'State' and 'Number of Schools' entry

rows_to_drop = ['State', 'Number of Schools']

sorted_highest_offense = highest_offense.drop(rows_to_drop).sort_values(ascending=False)
sorted_highest_offense

"""### Question 2: Which states have the highest overall referral and arrest rates?

Based on the dataset, the states with the highest referral and arrest intensity (calculated as the number of students referred or arrested per 100 schools) are:

***States with the highest *referrals* to law enforcement per 100 schools:***
1. Virginia (913 per 100 schools)
2. Florida (620 per 100 schools)
3. Pennsylvania (600 per 100 schools)

***States with the highest school-related *arrests* per 100 schools:***
1. Hawaii (228 per 100 schools)
2. Maryland (161 per 100 schools)
3. Nevada (141 per 100 schools)

Because statewide enrollment data was not included, referral intensity was calculated as the average number of students referred per school. Using a per-school metric allows for fair comparison across states of different sizes.
"""

# Look at the dataset
referred_disability_and_no.head()

arrests_disability_and_no.head()

# To get the highest overall referral and arrest rates we would need to create a new column that calculates
# the number of total students of each state divided by number of schools
referred_disability_and_no['referrals_per_100_schools'] = (referred_disability_and_no['Total Students Referred'] / referred_disability_and_no['Number of Schools']) * 100

arrests_disability_and_no['arrests_per_100_schools'] = (arrests_disability_and_no['Total Students Arrested'] / arrests_disability_and_no['Number of Schools']) * 100

# Print top 5 referrals per 100 schools and only show the 'State' and 'Referrals per 100 schools' columns
top_5_referrals = referred_disability_and_no.sort_values(by='referrals_per_100_schools', ascending=False)
top_5_referrals[['State', 'referrals_per_100_schools']].head(5)

# Do the same for arrests per 100 schools
top_5_arrests = arrests_disability_and_no.sort_values(by='arrests_per_100_schools', ascending=False)
top_5_arrests[['State', 'arrests_per_100_schools']].head(5)

"""### Question 3: What proportion of referrals result in an arrest by state?

Based on the combined dataset, the states with the highest referral to arrest rates are:
1. Hawaii (88%)
2. Connecticut (77%)
3. Indiana (57.9%)

and the states with the lowest referral to arrest rates are:
1. Puerto Rico (0%)
2. Wyoming (1.58%)
3. Alask (1.65%)
"""

# Combine both arrest and referred datasets to create a new dataset
combined = pd.merge(referred_disability_and_no, arrests_disability_and_no, on='State', suffixes=('_referred', '_arrests'))

combined.head()

# Create a new column the calculates the proportion of refferals that result in arrests by state
# Similar to finding overall referral/arrest rates, we divide the part/total -> arrests/referrals
combined['arrest_rate'] = (combined['Total Students Arrested'] / combined['Total Students Referred']) * 100

top_referral_to_arrest_rate = combined.sort_values(by='arrest_rate', ascending=False)
top_referral_to_arrest_rate[['State', 'arrest_rate']].head(10)

bottom_referral_to_arrest_rate = combined.sort_values(by='arrest_rate')
bottom_referral_to_arrest_rate[['State', 'arrest_rate']].head(10)

"""## Part 2: Disability and Racial Disparity

### Question 4: Are students with disabilities represented differently in arrests compared to referrals? (WIP)
"""

# Combine total students with only disability dataframe
total_and_disability_referrals = pd.merge(referred_disability, referred_disability_and_no, on='State', suffixes=('_total', '_disability'))

total_and_disability_referrals.head()

# Create a new column to calculate the proportionate of the referrals made to law enforcement nationally
total_and_disability_referrals['disabilities_proportion'] = (total_and_disability_referrals['Students With Disabilities Referred'] / total_and_disability_referrals['Total Students Referred']) * 100

total_and_disability_referrals[['State', 'disabilities_proportion']].head(10)

# Display the list in ascending order
disability_ref_percentage = total_and_disability_referrals.sort_values(by='disabilities_proportion', ascending=False)
disability_ref_percentage[['State', 'disabilities_proportion']].head(10)

# Do the same but this time for arrests and compare the percentage values
total_and_disability_arrests = pd.merge(arrests_disability, arrests_disability_and_no, on='State', suffixes=('_total', '_disability'))

total_and_disability_arrests.head()

# Create a new column to calculate the proportionate of the arrests made nationally
total_and_disability_arrests['disabilities_proportion'] = (total_and_disability_arrests['Students With Disabilities Arrested'] / total_and_disability_arrests['Total Students Arrested']) * 100

total_and_disability_arrests[['State', 'disabilities_proportion']].head(10)

# Display list in ascending order
disability_arrest_percentage = total_and_disability_arrests.sort_values(by='disabilities_proportion', ascending=False)
disability_arrest_percentage[['State', 'disabilities_proportion']].head(10)

# Compare the proportions of the two dataframes and calculate percent difference
total_and_disability_arrests['percent_difference'] = ((total_and_disability_arrests['disabilities_proportion'] - total_and_disability_referrals['disabilities_proportion']) / total_and_disability_referrals['disabilities_proportion']) * 100

# Check if total percent differneces show
total_and_disability_arrests[['State', 'percent_difference']].head(10)

# Count how many states have a negative percent difference
arrests_lower_than_referrals = total_and_disability_arrests['percent_difference'] < 0

# Count how many states have a positive percent difference
referrals_lower_than_arrests = total_and_disability_arrests['percent_difference'] > 0

# Display results
print(arrests_lower_than_referrals.sum())
print(referrals_lower_than_arrests.sum())

"""### Question 5: Which states show the largest disparity in referral and arrest representation between students with and without disabilities?

Based on the dataset, states where students with disabilities make up a higher share of referrals often also show a higher share of arrests involving these students. However, disparity is best understood as the difference between their share of referrals and their share of arrests.

1. One of the most notable findings is Vermont, where students with disabilities account for approximately 48.21% of referrals but 80.00% of arrests. This large increase indicates a substantial disparity, suggesting that students with disabilities are represented at a much higher rate in arrests compared to referrals within the state.

2. In contrast, Puerto Rico shows a different pattern. Students with disabilities account for about 50% of referrals, but do not show a similarly high share of arrests. This suggests a smaller disparity, as representation remains more consistent between referrals and arrests.

3. States such as Connecticut, Massachusetts, and Maine also show relatively high representation of students with disabilities in both referrals and arrests, though generally below 50%. These states appear consistently across both measures, but do not exhibit as large of a gap between referral and arrest representation as Vermont.

##### Referrals
"""

# Combine seperated dataframes -> disabilities df and no disabilities df
with_and_wihout_disabilities_ref = pd.merge(referred_disability, referred_no_disability, on='State', suffixes=('_with_disabilities', '_without_disabilities'))

with_and_wihout_disabilities_ref.head()

# Show only 'Students With Disabilities Referred' and 'Students Without Disabilities Referred'
with_and_wihout_disabilities_ref[['State', 'Students With Disabilities Referred','Students Without Disabilities Referred']].head(10)

# Check whether there are any columns where students with disabilities have a higher count than students without disabilities
condition = with_and_wihout_disabilities_ref['Students With Disabilities Referred'] > with_and_wihout_disabilities_ref['Students Without Disabilities Referred']
filtered_df = with_and_wihout_disabilities_ref.loc[condition]
filtered_df[['State']]

# Check to see if there are any columns where the percentage of students with disabilities referred is high (60-70%)
percent_disabilities_referred = (with_and_wihout_disabilities_ref['Students With Disabilities Referred'] / (with_and_wihout_disabilities_ref['Students Without Disabilities Referred'] + with_and_wihout_disabilities_ref['Students With Disabilities Referred'])) * 100
with_and_wihout_disabilities_ref['percent_disabilities_referred'] = percent_disabilities_referred

# Check percent values in ascending order
percent_disabilities_referred_df = with_and_wihout_disabilities_ref.sort_values(by='percent_disabilities_referred', ascending=False)
percent_disabilities_referred_df[['State', 'percent_disabilities_referred']].head(10)

"""##### Arrests"""

# Combine seperated dataframes -> disabilities df and no disabilities df
with_and_wihout_disabilities_arrests = pd.merge(arrests_disability, arrests_no_disability, on='State', suffixes=('_with_disabilities', '_without_disabilities'))

with_and_wihout_disabilities_arrests.head()

# Show only 'Students With Disabilities Referred' and 'Students Without Disabilities Referred'
with_and_wihout_disabilities_arrests[['State', 'Students With Disabilities Arrested','Students Without Disabilities Arrested']].head(10)

# Check whether there are any columns where students with disabilities have a higher count than students without disabilities
condition = with_and_wihout_disabilities_arrests['Students With Disabilities Arrested'] > with_and_wihout_disabilities_arrests['Students Without Disabilities Arrested']
filtered_df = with_and_wihout_disabilities_arrests.loc[condition]
filtered_df[['State']]

# Check to see if there are any columns where the percentage of students with disabilities referred is high (60-70%)
percent_disabilities_arrested = (with_and_wihout_disabilities_arrests['Students With Disabilities Arrested'] / (with_and_wihout_disabilities_arrests['Students Without Disabilities Arrested'] + with_and_wihout_disabilities_arrests['Students With Disabilities Arrested'])) * 100
with_and_wihout_disabilities_arrests['percent_disabilities_arrested'] = percent_disabilities_arrested

# Check percent values in ascending order
percent_disabilities_arrested_df = with_and_wihout_disabilities_arrests.sort_values(by='percent_disabilities_arrested', ascending=False)
percent_disabilities_arrested_df[['State', 'percent_disabilities_arrested']].head(10)

percent_disabilities_arrested_df['disparity_gap'] = with_and_wihout_disabilities_arrests['percent_disabilities_arrested'] - with_and_wihout_disabilities_ref['percent_disabilities_referred']

percent_disabilities_arrested_df.head(10)

"""## Key Findings and Interpretation

This analysis of school-related referrals and arrests reveals several consistent patterns across states, particularly in the types of offenses reported and the representation of students with disabilities in disciplinary actions.

- First, non-weapon-related offenses, such as physical attacks without a weapon and threats of physical attack, were the most commonly reported incidents nationwide. This suggests that the majority of school disciplinary issues involve lower-severity offenses rather than those involving weapons.

- Second, when adjusting for state size by calculating referrals and arrests per 100 schools, certain states such as Virginia, Florida, and Hawaii emerged as having higher levels of disciplinary activity. This highlights the importance of using normalized measures rather than raw counts when comparing across states.

- Most notably, students with disabilities make up a substantial share of both referrals and arrests across many states. In some cases, their representation increases from referrals to arrests. For example, Vermont showed a significant disparity, where students with disabilities accounted for approximately 48.21% of referrals but 80.00% of arrests. This pattern suggests that in certain states, students with disabilities may experience a higher level of escalation within the disciplinary process.

- In contrast, other regions such as Puerto Rico showed high representation in referrals but not in arrests, indicating more consistent outcomes across stages of disciplinary action. Additionally, states like Connecticut, Massachusetts, and Maine consistently showed elevated representation of students with disabilities in both referrals and arrests, though with smaller differences between the two.

Overall, these findings suggest that while disciplinary actions are common across all states, there are notable differences in how students with disabilities are represented and how outcomes progress from referral to arrest. These patterns highlight potential areas for further investigation into equity and disciplinary practices across school systems.

## Additional Questions for Future Analysis

Another potential area for further analysis is examining how race and ethnicity intersect with disability status in school disciplinary actions.

For example:


```
Among students with disabilities, which racial and ethnic groups account for the largest share of referrals?
```

Because the dataset includes breakdowns by race and ethnicity, this analysis could provide deeper insight into how disciplinary actions vary across different demographic groups. Exploring these patterns may help identify whether certain groups of students with disabilities are more frequently represented in referrals, which could point to broader disparities within the education system.
"""